pull_request_rules:
  - name: automatic merge for Dependabot pull requests once CI passes
    conditions:
      - author=dependabot[bot]
      - base=main
      - "check-success=ci/circleci: build"
      - "check-success=ci/circleci: shellcheck"
      - "check-success=ci/circleci: json-lint"
      - "check-success=ci/circleci: erb-lint"
      - "check-success=ci/circleci: docker-compose-validate"
      - "check-success=ci/circleci: prometheus-config-check"
    actions:
      merge:
        method: squash
