pull_request_rules:
  - name: automatic merge for Dependabot pull requests once CI passes
    conditions:
      - author=dependabot[bot]
      - base=main
      - "check-success=build"
      - "check-success=shellcheck"
      - "check-success=json-lint"
      - "check-success=erb-lint"
      - "check-success=docker-compose-validate"
      - "check-success=prometheus-config-check"
    actions:
      merge:
        method: squash
