pull_request_rules:
  - name: automatic merge for Dependabot pull requests once CI passes
    conditions:
      - author=dependabot[bot]
      - base=main
      - "check-success=CI / build"
      - "check-success=CI / shellcheck"
      - "check-success=CI / json-lint"
      - "check-success=CI / erb-lint"
      - "check-success=CI / docker-compose-validate"
      - "check-success=CI / prometheus-config-check"
    actions:
      merge:
        method: squash
